"""empty message

Revision ID: 346b5bb3dc57
Revises: 7b7c7ca80c87
Create Date: 2021-01-21 19:33:15.164261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346b5bb3dc57'
down_revision = '7b7c7ca80c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
