"""empty message

Revision ID: 7b7c7ca80c87
Revises: 
Create Date: 2021-01-19 20:24:34.435432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7c7ca80c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hobby', sa.String(), nullable=True),
    sa.Column('vaccination', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
